### PR TITLE
Fix for Profile Name Issue in Nightscout Integration

### PR DESCRIPTION
**Pull request by bjorkert**
We've identified a critical issue in the Nightscout integration (up to version 15.0.2), where uploading a profile through the API with a name containing a "." character leads to a crash. This PR addresses this problem by introducing a fix that automatically replaces any "." in profile names with "_".

The solution is implemented through a new function, sanitizedName, designed for modifying profile names. This function is currently focused on replacing the "." character, but it's structured for easy extension. Should we encounter other problematic characters in the future, we can readily add them to this function's replacement logic.

This change ensures greater stability in our interactions with the Nightscout API and prevents potential crashes due to profile naming issues.

### CODE REVIEW

**Comment by marionbarker** [comment]
Tested function on Loop test phone with associated Nightscout site (14.2.6).
Loop phone: Added new profile with name:
* Try to insert a period 14.3

On the Loop phone, the profile is automatically renamed:
* Try to insert a period 14_3

This profile uploads with no errors in Nightscout.
(Prior to this, wouild get a 502 Bad Gateway error when uploading a profile name with an embedded . through the api.)

**Comment by marionbarker** [comment]
This needs to be fixed: 
* This doesn't use sanitizedName when loading and old profile that contains a "." character - 502 Bad Gateway

**Comment by bjorkert** [comment]
> This needs to be fixed:
> 
> * This doesn't use sanitizedName when loading and old profile that contains a "." character - 502 Bad Gateway

Old profiles are now loaded (and displayed) with the replacement of .->_. Verified that a current profile with . is displayed as selected in the list and sent correctly to Nightscout.

**Comment by marionbarker** [comment]
That fix worked. All existing profiles that contain "." are changed to "_" when profiles are shown.

**Pull request merged**
