### PR TITLE
Patch for dexcom one+

### PR DESCRIPTION
**Pull request by bjorkert**

### CODE REVIEW

**Comment by marionbarker** [comment]
Tested for main and dev.

**Comment by VladStanciu** [comment]
hello,
how to make this patch work?
I copy paste the lines but is not working, what I do wrong or how to do it wright ?

**Comment by marionbarker** [comment]
> hello, how to make this patch work? I copy paste the lines but is not working, what I do wrong or how to do it wright ?

You need to follow these directions:

General information about using Loop and Learn customizations:
* https://www.loopandlearn.org/custom-code/

Specific information about adding a patch to the build_loop.yml file for main branch
* https://www.loopandlearn.org/custom-code/#template

**Comment by marionbarker** [comment]
@VladStanciu 
Another alternative is to build the dev branch which is pretty stable. It already has Dexcom One+ included as well as a bunch of other fixes.

This link lists some of the updates:
* https://loopkit.github.io/loopdocs/version/development/#updates-in-dev

This link has instruction on how to build he dev branch:
* https://loopkit.github.io/loopdocs/gh-actions/build-dev-browser/

**Comment by VladStanciu** [comment]
Thank you for your support, I will try to do it

**Comment by VladStanciu** [comment]
is there a video where is explained how to do it? or step by step tutorial?

**Pull request merged**
